### ISSUE TITLE
東京 Crystal 勉強会 #3 を開催する

### ISSUE THREAD

**Issue by pine** [crystal-jp/study_session#1]
# タスク一覧

詳細に議論する必要があるものについては、別途 Issue を切ってリンクを貼る。
## 開催2ヶ月前
- [x] 開催日を決定する -> 1/22
- [x] 勉強会会場を手配する -> rosylilly さんに託した
- [x] Connpass に掲載する内容を決める
  - [x] 人数 -> 80
  - [x] 場所 -> done
  - [x] 時間 -> 19:30 ~ 21:00
  - [x] 内容
  - [x] 発表者
  - [x] アンケート -> 書いた
## 開催1ヶ月前 (~ 12/22)
- [x] Connpass のイベントページを公開する
- [x] 開催会場の社内に向けて告知を行う
- [x] 知り合いつてで告知しまくる
- [x] 会場内の案内のビルへの申請を出す
- [x] 当日受付を手伝ってくれる人を探す
- [x] 懇親会の参加費を決める
## 開催一週間前
- [x] 参加者に対してリマインドメッセージを送る
## 開催直前
- [x] カクヤスで飲み物を手配する
- [x] ドミノ・ピザを手配する
- [x] 参加者向けの紙皿、コップを手配する
- [x] WiFi 情報の掲示を用意する
## 開催当日
- [x] 参加者のリストを準備する
- [x] WiFi 情報を掲示する

**Comment by makenowjust** [comment]
:+1:

**Comment by karupanerura** [comment]
http://crystal.connpass.com/event/22754/

**Comment by pine** [comment]
:tada: :tada: :tada:
