### ISSUE TITLE
Crystal Advent Calendar 2015 を埋める

### ISSUE THREAD

**Issue by pine** [crystal-jp/study_session#2]
埋めたい
http://www.adventar.org/calendars/800

**Comment by pine** [comment]
第一弾: 過去に LT にした方にお願いして回る
http://crystal.connpass.com/event/17496/
http://crystal.connpass.com/event/19339/

**Comment by pine** [comment]
あと 7 記事…! あとはきっと @rosylilly さんがなんとかしてくれると信じてる。

**Comment by karupanerura** [comment]
ろーじりりーさんすごいー

**Comment by rosylilly** [comment]
マジで

**Comment by 5t111111** [comment]
1つ埋めた！

**Comment by pine** [comment]
:+1:

**Comment by pine** [comment]
埋まったので closed :tada:

**Comment by makenowjust** [comment]
:+1:
