### ISSUE TITLE
第六回の開催

### ISSUE THREAD

**Issue by makenowjust** [crystal-jp/study_session#3]
とりあえずissueを立てる。

/cc @karupanerura @TobiasGSmollett

**Comment by karupanerura** [comment]
DeNA Tech STUDIOという支援制度もあります:
https://denatechstudio.connpass.com/
https://fullswing.dena.com/techstudio/

**Comment by masak1yu** [comment]
古巣のドリコムも、会場（アルコタワー）は言えば貸してもらえると思いますのでよろしくご検討ください。

**Comment by yoshiyuki-tsuchida** [comment]
トビアスさん：「その日に場所が空いてたら取れます！」

とのこと。

**Comment by at-grandpa** [comment]
トビアスさん：「その日に場所が空いてたら取れます！」

とのこと。

**Comment by at-grandpa** [comment]
日付だけ決めてしまって、そこから場所の調整ですかね。

**Comment by at-grandpa** [comment]
（技術書典の締め切り後が良さそう？？

**Comment by makenowjust** [comment]
なぜ？

**Comment by at-grandpa** [comment]
* 技術書典執筆者と勉強会参加者の被り率が高そう？
* 勉強会資料作成期間を考えると１ヶ月後あたりが良さそう？
* いろいろ被る結果、参加者が少なくなりそう？

と思ったのですが、よくよく考えてみると、

* 影響範囲は小さそう
* 技術書典締め切り後だと、相当先になってしまう

なので、２月下旬〜３月上旬あたりはどうでしょうか。もうちょっと直近でもいけますかね。

**Comment by karupanerura** [comment]
うちも空いてれば基本つかえます！ただ、2月下旬~3月上旬はYAPC::Okinawa直前でぼくが時間とれない可能性があります。。

**Comment by makenowjust** [comment]
これ、今からやるとしたら四月の二週目くらいかなと思うのですが、その辺だとどうでしょうか？
