### ISSUE TITLE
第五回 振り返り

### ISSUE THREAD

**Issue by at-grandpa** [crystal-jp/study_session#4]
# 開催まとめ

* connpass
  * https://crystal.connpass.com/event/70446/
* 参加者11名
* 注文した食事類
  * ピザL ３枚
  * ポテトフライL
  * コンソメポテトL
  * シーザーサラダ
  * チキンナゲットL ２つ
  * ajitoのお酒
* まとめ記事
  * http://at-grandpa.hatenablog.jp/entry/2017/12/01/183114
* やったこと
  * 「ゆるーい会」にしたかった
  * 発表と懇親会とを分けなかった
    * もっと大人数の場合は、もっと厳格に発表と懇親会をわけたほうがうまくいくかも
  * LTとはいえ、厳格な時間制限は設けなかった
  * モブプロ
    * 盛り上がった
    * 11名は多かったかも
      * ３〜４人のチームに分けたほうがよかったかも
    * yesコマンドの題材は良くなかった
      * 発展しなかった
      * どんな題材が良かったのかはわからない
* 懇親会も盛り上がってよかった

# 今後に向けて

* 他の会場で開催しても良さそう
* LTはもちろん面白いが、それだけでなく、何か他に盛り上がるコンテンツがないか模索
  * 「このPRは何をどう改善しているのか」をみんなでひたすら読みまくるとか？
* 参加人数を増やしたい＆参加ハードルを下げたい
  * 日頃から情報発信して広めていくしかないかなぁ
  * 人気勉強会から学ぶ

**Comment by makenowjust** [comment]
モブプロに関してなのですけど、Atomをインストールしておいてほしいという旨を事前に告知してもらえたら良かったな、と思います。

**Comment by at-grandpa** [comment]
> Atomをインストールしておいてほしいという旨を事前に告知してもらえたら良かったな

そうですね。

今回は「ちょっとしたサプライズ」的なことも考えていたので、告知しませんでした。それが裏目に出てしまいました。本質はやはり「みなさんに参加してもらうこと」なので、次の機会は事前告知しましょう！
